### PR TITLE
Added MSI Path parameter

### PR DESCRIPTION
**Pull request by dmcwee**
Added a parameter to specify the path to the Unified Agent's MSI file as well as adding some additional error checks to handle if the msi (dev or regular) cannot be found at the path and stop the script's execution.

Script's signature was not updated.

### CODE REVIEW

**Review by pahuijbr — COMMENTED** [review]
Hi @dmcwee can you please tell us if any scenario is blocked unless this change is applied?

**Comment by dmcwee** [comment]
@pahuijbr adding the path for the MSI does not specifically enable a blocked scenario but does align with the way the onboarding script's path can be provided, and it does allow customers to place the MSI in the same location they may host other installer files in their organization.  This also help clarify where the MSI should be loaded, otherwise users of the script have to read the entire script to determine the right location for placing the MSI.

The other change is that the original script only checks if it is not in dev mode and the MSI exists.  However, if the MSI does not exist then the script assumes the use of Dev Mode and attempts to execute the Dev MSI (regardless of if $DevMode is present or if the devmode msi exists).  The update checks the status of DevMode along with the DevMode MSI path to validate the intent and existence and if those checks fail then the script will report an error rather than proceeding.

**Comment by dmcwee** [comment]
@pahuijbr - Another issue if the customer is putting the script into SCCM there is no way to control where the MSI is going to be located.  Solution is the customer must manually edit the script to the location where SCCM could access it.

**Comment by pahuijbr** [comment]
Please check latest script revision, should solve for same/similar issue

**Pull request closed without merging**
